### PR TITLE
vimc-5265 create YT tickets on report run failure

### PR DESCRIPTION
**Pull request by hillalex**
If a diagnostic report fails to run for any reason, create a YT ticket with the summary "Run, check & share diagnostic report..."

This PR adds an error callback to the run function as well as a success callback, and then invokes it from every error path.

### CODE REVIEW

**Review by EmmaLRussell — COMMENTED** [review]
This looks great to me. 

I wonder if it would be worth adding a special tag for tickets for reports which failed to run as well, doesn't seem like there's much to distinguish successful from failed report tickets just now, just the slightly different summary.

Maybe in the case of failure it would be good to include the report run key in the ticket description so that it would be easier to find in the logs. And possibly an error message as well. Or maybe that would be overkill - since the assignee is just going to re-run and see any persistent error for themselves.

**Comment by hillalex** [comment]
> This looks great to me.
> 
> I wonder if it would be worth adding a special tag for tickets for reports which failed to run as well, doesn't seem like there's much to distinguish successful from failed report tickets just now, just the slightly different summary.
> 
> Maybe in the case of failure it would be good to include the report run key in the ticket description so that it would be easier to find in the logs. And possibly an error message as well? Or maybe that would be overkill - since the assignee is just going to re-run and see any persistent error for themselves.

Yeah good shout, some kind of message would be nice. I'll run it by Katy.

**Comment by hillalex** [comment]
I deployed this on prod to see how it works and there's a flaw - when runs are cancelled it still creates tickets! So let me fix that before we merge this.

**Comment by hillalex** [comment]
@EmmaLRussell ok, ready for review :)

**Review by EmmaLRussell — APPROVED** [review]
LGTM. In the notes for the last Tech call, Kim mentioned setting the Implementer in the tickets as well. Want to do that here or in another branch?

**Comment by hillalex** [comment]
> LGTM. In the notes for the last Tech call, Kim mentioned setting the Implementer in the tickets as well. Want to do that here or in another branch?

Oh thanks, may as well add it here and then we can get that all deployed

**Review by EmmaLRussell — APPROVED** [review]

**Pull request merged**
